<?php
/**
 * Global application configuration.
 */

define('APP_NAME', 'PHP Visual Page Builder');
define('APP_ROOT', dirname(__DIR__));
define('APP_BASE_URL', rtrim(str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'] ?? '/')), '/'));

// Resolve base URL correctly regardless of which script includes this file.
// We compute it once from the known project folder name to avoid path drift
// when config.php is included from api/ or other subfolders.
if (!defined('APP_URL')) {
    $scriptDir = str_replace('\\', '/', __DIR__);
    $projectRoot = str_replace('\\', '/', APP_ROOT);
    $docRoot = str_replace('\\', '/', $_SERVER['DOCUMENT_ROOT'] ?? '');
    $relative = '';
    if ($docRoot !== '' && strpos($projectRoot, $docRoot) === 0) {
        $relative = substr($projectRoot, strlen($docRoot));
    }
    define('APP_URL', '/' . trim($relative, '/'));
}

define('UPLOADS_DIR', APP_ROOT . '/uploads/images');
define('UPLOADS_URL', APP_URL . '/uploads/images');
define('EXPORTS_DIR', APP_ROOT . '/exports');
define('TEMPLATES_DIR', APP_ROOT . '/templates');
define('GRAPESJS_URL', APP_URL . '/grapesjs');
define('ASSETS_URL', APP_URL . '/assets');

// Installation state: config/installed.php is generated by the setup.php
// wizard once the admin has entered database credentials. Its absence
// means the app has never been installed (or was reset), so every entry
// point should redirect to the wizard instead of trying to hit a database
// that may not exist yet.
define('INSTALL_CONFIG_FILE', APP_ROOT . '/config/installed.php');
if (file_exists(INSTALL_CONFIG_FILE)) {
    require_once INSTALL_CONFIG_FILE;
    define('APP_INSTALLED', true);
} else {
    define('APP_INSTALLED', false);
}

define('MAX_UPLOAD_BYTES', 5 * 1024 * 1024); // 5 MB
define('ALLOWED_IMAGE_EXT', ['jpg', 'jpeg', 'png', 'gif', 'webp']);
define('ALLOWED_IMAGE_MIME', [
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/webp',
]);

error_reporting(E_ALL);
ini_set('display_errors', '0'); // never leak errors to output; log instead
ini_set('log_errors', '1');

date_default_timezone_set('Asia/Jakarta');

// Secure session configuration must happen before session_start().
if (session_status() === PHP_SESSION_NONE) {
    session_set_cookie_params([
        'lifetime' => 0,
        'path' => APP_URL !== '' ? APP_URL . '/' : '/',
        'domain' => '',
        'secure' => isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off',
        'httponly' => true,
        'samesite' => 'Lax',
    ]);
    session_name('ppb_session');
    session_start();
}
