<?php
/**
 * Helpers for turning stored page HTML/CSS into portable static output:
 * finding referenced uploaded images, rewriting absolute upload URLs to
 * relative "images/..." paths, and rewriting internal page links
 * ("/about") to exported filenames ("about.html").
 */

/**
 * Find every uploads/images/<file> reference inside HTML or CSS text.
 * Returns an array of unique filenames (basename only).
 */
function exporter_find_used_images(string $html, string $css): array
{
    $filenames = [];
    // Image src/url() values may be site-relative ("/app/uploads/images/x.png")
    // or absolute ("http://host:port/app/uploads/images/x.png") depending on
    // how they were authored — match an optional scheme+host prefix too.
    $pattern = '#(?:https?://[^/"\'\s]+)?' . preg_quote(UPLOADS_URL, '#') . '/([a-zA-Z0-9_\-\.]+)#';

    if (preg_match_all($pattern, $html, $m)) {
        foreach ($m[1] as $f) {
            $filenames[$f] = true;
        }
    }
    if (preg_match_all($pattern, $css, $m)) {
        foreach ($m[1] as $f) {
            $filenames[$f] = true;
        }
    }

    return array_keys($filenames);
}

/**
 * Rewrite uploads URLs to a relative "images/<file>" path (used inside
 * exported HTML/CSS so the ZIP is portable).
 */
function exporter_rewrite_upload_urls(string $content): string
{
    $pattern = '#(?:https?://[^/"\'\s]+)?' . preg_quote(UPLOADS_URL, '#') . '/([a-zA-Z0-9_\-\.]+)#';
    return preg_replace($pattern, 'images/$1', $content);
}

/**
 * Rewrite internal links like href="/about" or href="/" into the exported
 * filename ("about.html", "index.html") using the given slug => filename
 * map. Links that don't match a known slug are left untouched.
 *
 * @param array<string,string> $slugToFilename
 */
function exporter_rewrite_internal_links(string $html, array $slugToFilename): string
{
    return preg_replace_callback(
        '/href=(["\'])(\/[a-zA-Z0-9_\-\/]*)\1/',
        function ($matches) use ($slugToFilename) {
            $quote = $matches[1];
            $slug = $matches[2];
            if (isset($slugToFilename[$slug])) {
                return 'href=' . $quote . $slugToFilename[$slug] . $quote;
            }
            return $matches[0];
        },
        $html
    );
}

/**
 * Wrap a page's HTML body + CSS link into a full HTML document.
 */
function exporter_build_html_document(string $title, string $bodyHtml, string $cssHref): string
{
    $safeTitle = htmlspecialchars($title, ENT_QUOTES, 'UTF-8');
    return "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"UTF-8\">\n"
        . "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        . "<title>{$safeTitle}</title>\n"
        . "<link rel=\"stylesheet\" href=\"{$cssHref}\">\n"
        . "</head>\n<body>\n{$bodyHtml}\n</body>\n</html>\n";
}

/**
 * Wrap a page's HTML body in a PHP file. The builder never embeds
 * PHP code sourced from the editor — this is a static wrapper only.
 */
function exporter_build_php_document(string $title, string $bodyHtml, string $cssHref): string
{
    $safeTitle = htmlspecialchars($title, ENT_QUOTES, 'UTF-8');
    return "<?php\n// Generated by PHP Visual Page Builder\n// Edit below the HTML/CSS output from the visual editor,\n"
        . "// or replace {{placeholders}} with PHP variables as needed.\n?>\n"
        . "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"UTF-8\">\n"
        . "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        . "<title>{$safeTitle}</title>\n"
        . "<link rel=\"stylesheet\" href=\"{$cssHref}\">\n"
        . "</head>\n<body>\n{$bodyHtml}\n</body>\n</html>\n";
}
